// flow-typed signature: fa85a113756c49bab29759c32d38df56
// flow-typed version: <<STUB>>/passport-google-oauth20_v^1.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-google-oauth20'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-google-oauth20' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-google-oauth20/lib/errors/googleplusapierror' {
  declare module.exports: any;
}

declare module 'passport-google-oauth20/lib/errors/userinfoerror' {
  declare module.exports: any;
}

declare module 'passport-google-oauth20/lib/index' {
  declare module.exports: any;
}

declare module 'passport-google-oauth20/lib/profile/googleplus' {
  declare module.exports: any;
}

declare module 'passport-google-oauth20/lib/profile/openid' {
  declare module.exports: any;
}

declare module 'passport-google-oauth20/lib/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-google-oauth20/lib/errors/googleplusapierror.js' {
  declare module.exports: $Exports<'passport-google-oauth20/lib/errors/googleplusapierror'>;
}
declare module 'passport-google-oauth20/lib/errors/userinfoerror.js' {
  declare module.exports: $Exports<'passport-google-oauth20/lib/errors/userinfoerror'>;
}
declare module 'passport-google-oauth20/lib/index.js' {
  declare module.exports: $Exports<'passport-google-oauth20/lib/index'>;
}
declare module 'passport-google-oauth20/lib/profile/googleplus.js' {
  declare module.exports: $Exports<'passport-google-oauth20/lib/profile/googleplus'>;
}
declare module 'passport-google-oauth20/lib/profile/openid.js' {
  declare module.exports: $Exports<'passport-google-oauth20/lib/profile/openid'>;
}
declare module 'passport-google-oauth20/lib/strategy.js' {
  declare module.exports: $Exports<'passport-google-oauth20/lib/strategy'>;
}
